### ISSUE TITLE
Error when loading empty bank

### ISSUE THREAD

**Issue by creatorfromhell** [creatorfromhell/TheNewEconomy#22]
This'll be an easy fix, but a bug nonetheless.

**Comment by creatorfromhell** [comment]
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.tnerevival.utils.MISCUtils.itemstackFromString(MISCUtils.java:188) ~[?:?]
	at com.github.tnerevival.utils.BankUtils.fromString(BankUtils.java:87) ~[?:?]
	at com.github.tnerevival.core.SaveManager.loadFlatFile(SaveManager.java:392) ~[?:?]
	at com.github.tnerevival.core.SaveManager.load(SaveManager.java:244) ~[?:?]
	at com.github.tnerevival.core.SaveManager.<init>(SaveManager.java:53) ~[?:?]
```
Just for reference. The slot number isn't being saved when the bank inventory is empty.
